[build]
publish = ".next"

[[redirects]]
  from = "/istanbul"
  to = "https://devconnect.org/schedule"
  status = 302
  force = true

[[redirects]]
  from = "/host"
  to = "https://ef-events.notion.site/How-to-organize-an-event-during-Devconnect-4175048066254f48ae85679a35c94022"
  status = 302
  force = true

# 26th June 2023
[[redirects]]
  from = "/edition/amsterdam"
  to = "https://devconnect.org/amsterdam"
  status = 302
  force = true

# 26th June 2023
[[redirects]]
  from = "/edition/istanbul"
  to = "https://devconnect.org/schedule"
  status = 302
  force = true